# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: ""
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: realdlee@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/grand_canyon.jpg"

name: 'David Lee'
author: 'David Lee'
author_image: "/assets/images/author.jpeg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/real_dlee
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/realdlee
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

